<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="5" assertions="4" errors="2" warnings="0" failures="0" skipped="0" time="0.046185">
    <testsuite name="App" tests="5" assertions="4" errors="2" warnings="0" failures="0" skipped="0" time="0.046185">
      <testsuite name="ExampleDatabaseTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\database\ExampleDatabaseTest.php" tests="2" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="0.032787">
        <testcase name="testModelFindAll" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\database\ExampleDatabaseTest.php" line="17" assertions="0" time="0.030308">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testModelFindAll
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

D:\xampp\htdocs\Tourism-Rizal\system\Database\BaseConnection.php:427
D:\xampp\htdocs\Tourism-Rizal\system\Database\SQLite3\Connection.php:59
D:\xampp\htdocs\Tourism-Rizal\system\Test\DatabaseTestTrait.php:74
D:\xampp\htdocs\Tourism-Rizal\system\Test\DatabaseTestTrait.php:54
D:\xampp\htdocs\Tourism-Rizal\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
        <testcase name="testSoftDeleteLeavesRow" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\database\ExampleDatabaseTest.php" line="28" assertions="0" time="0.002479">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testSoftDeleteLeavesRow
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

D:\xampp\htdocs\Tourism-Rizal\system\Database\BaseConnection.php:427
D:\xampp\htdocs\Tourism-Rizal\system\Database\SQLite3\Connection.php:59
D:\xampp\htdocs\Tourism-Rizal\system\Test\DatabaseTestTrait.php:74
D:\xampp\htdocs\Tourism-Rizal\system\Test\DatabaseTestTrait.php:54
D:\xampp\htdocs\Tourism-Rizal\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
      </testsuite>
      <testsuite name="ExampleSessionTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\session\ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.002352">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\session\ExampleSessionTest.php" line="11" assertions="1" time="0.002352"/>
      </testsuite>
      <testsuite name="HealthTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\unit\HealthTest.php" tests="2" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.011047">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\unit\HealthTest.php" line="13" assertions="1" time="0.001877"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="D:\xampp\htdocs\Tourism-Rizal\tests\unit\HealthTest.php" line="18" assertions="2" time="0.009169"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
